### ISSUE TITLE
Website improvements

### ISSUE THREAD

**Issue by trombonehero** [CTSRD-SOAAP/soaap#17]
On the SOAAP "Getting started" page, there is an error in the libxo instructions: `./configure` should be `../configure`. Also, the instructions can be simplified and de-kg365-path-ified by changing the line in question to:

```
[me@mymachine ~/workspace/soaap/libxo/build]$ ../configure --prefix=`pwd`/../install
```

Also, underneath "LLVM/Clang", I think that the -idirafter flags are unnecessary: I certainly don't need them when building on my freshly-installed FreeBSD 10.1 box.

**Comment by kgudka** [comment]
This is now been fixed.
