### ISSUE TITLE
libtool errors

### ISSUE THREAD

**Issue by trombonehero** [CTSRD-SOAAP/soaap#19]
When compiling libxo according to the SOAAP instructions on a non-vica FreeBSD machine, I see the following `libtool` errors:

```
libtool: Version mismatch error.  This is libtool 2.4.5, but the
libtool: definition of this LT_INIT comes from libtool 2.4.2.
libtool: You should recreate aclocal.m4 with macros from libtool 2.4.5
libtool: and run autoconf again.
```

It looks like `pkg` is up to `libtool-2.4.5`, but there is something 2.4.2-specific about the m4 files included in `libxo`'s repository. Could the SOAAP instructions be extended to include whatever `autoreconf` magic is required to re-generate these m4 files?

**Comment by trombonehero** [comment]
I'm just sent a pull request to libxo upstream that would fix the problem by removing (stale) generated files from the libxo repository. In the meantime, perhaps the SOAAP instructions could tell you to:

```shell
rm -rf configure m4
```
?

**Comment by kgudka** [comment]
I've now added this cleanup when configuring libxo as part of the ExternalProject build in CMake
