### ISSUE TITLE
Duplicate vulnerability annotations

### ISSUE THREAD

**Issue by trombonehero** [CTSRD-SOAAP/soaap#3]
SOAAP tells me:

Function "WebCore::RangeBoundaryPoint::toPosition() const" has past-vulnerability annotations for "[Cr issue #51602,Cr issue #51602,Cr issue #51602,Cr issue #51602,Cr issue #51602,Cr issue #51602,Cr issue #51602,Cr issue #51602,Cr issue #51602,Cr issue #51602,Cr issue #51602,Cr issue #51602,Cr issue #51602,Cr issue #51602,Cr issue #51602,Cr issue #51602,Cr issue #51602,Cr issue #51602]".

This might be because it calls or otherwise uses annotated things several times, but I only need to know about it once.

**Comment by kgudka** [comment]
This was resolved in 849a9a96d7bc69539d9b22414be4647b90dc7db2.
