### ISSUE TITLE
Output null values as 'null', not '"null"'

### ISSUE THREAD

**Issue by trombonehero** [CTSRD-SOAAP/soaap#35]
I don't know if it's a SOAAP issue or a libxo limitation, but when SOAAP emits information about something that's not sandboxed, it emits:

```json
"sandbox": "null"
```

rather than:
```json
"sandbox": null
```

Therefore, consumers of SOAAP JSON think that these calls are happening inside a sandbox, but that the sandbox is named `"null"`.

**Comment by kgudka** [comment]
Fixed in e68f1c8f79fd7efb84d0c9a9ddfcaf6018284ac5
