### ISSUE TITLE
Don't require fake sandboxes

### ISSUE THREAD

**Issue by trombonehero** [CTSRD-SOAAP/soaap#8]
If I reference a sandbox in a SOAAP annotation (e.g., `__soaap_private("network")`), the annotation should work even if I don't explicitly create the sandbox anywhere. In Chromium, I annotated a socket a being private to the `network` sandbox even though it doesn't exist so that I can observe all of the code that reads from libevent TCP sockets.

A warning would be fine (not a "something wrong with your program" warning, but a "something possibly wrong in your use of SOAAP" warning), but I would prefer not to add unreachable functions to a program just to enable a particular analysis.

**Comment by kgudka** [comment]
This was resolved by ae0540766ddc37afdc8744d954d6a1c612f56db5.
